# Generated by Django 4.0.1 on 2022-02-21 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_alter_case_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='updatedon',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
